### ISSUE TITLE
Response status code does not indicate success: 429 (Too Many Requests)

### ISSUE THREAD

**Issue by Vishu24** [MrRoundRobin/telegram.bot.examples#11]
Any once tell me what is the limit to send message on per minute or per day or any thing else?

**Comment by MrRoundRobin** [comment]
@Vishu24 https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this

**Comment by Vishu24** [comment]
@MrRoundRobin  Thank you
