### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by KennyNL** [MrRoundRobin/telegram.bot.examples#3]
How can we use this in groups? How would I retreive the Chat ID?
I can talk with the bot in a normal chat but It doesn't reply in a group or a supergroup.

Current code:
https://github.com/KennyNL/Clevergram

**Comment by MrRoundRobin** [comment]
did you read [this](https://core.telegram.org/bots#privacy-mode)

**Comment by KennyNL** [comment]
No I didn't yet. Thanks man :)

**Comment by KennyNL** [comment]
Fixed, thanks!
