### ISSUE TITLE
How to send 30 in 1 second to different user?

### ISSUE THREAD

**Issue by Vishu24** [MrRoundRobin/telegram.bot.examples#37]
I have one application in which i need to send approx. 30000  Msg/hr.  [text + image]. How can i achieve this?

If you're sending bulk notifications to multiple users, the API will not allow more than 30 messages per second or so. 

Currently I am sending message one by one. so it take 1 min to send 20 to 25 message [text+image].  As per telegram we can send 30 msg per second to different user. I want to achieve this limit without blocking bot.

Thanks.

**Comment by MrRoundRobin** [comment]
@Vishu24 https://core.telegram.org/bots/faq#how-can-i-message-all-of-my-bot-39s-subscribers-at-once

**Comment by Vishu24** [comment]
Thank for you replay.
I read that url. But I need sample code, how to send 30 msg in 1 second to different user?

**Comment by verdesgrobert** [comment]
@Vishu24 I think the slowness is not related to telegram servers but to your client or the network that connects you to telegram servers which doesn't let you reach 30msg/second.
I'd say that text+image upload 20-25 times is not possible with standard ADSL connection.

**Comment by Vishu24** [comment]
@verdesgrobert  So it is not possible to even send text 30 message in 1 second.
