### ISSUE TITLE
Send message(any type) to groups

### ISSUE THREAD

**Issue by mehdiyahyavi** [MrRoundRobin/telegram.bot.examples#68]
hi.
i want to send Text message or send a photo message to any of groups that i have Group Linke like : 
https://t.me/joinchat/---SQ9uXj5fZ8CjjF1g
there's the question: i want to send to group without adding my bot to group. in other word, i want to send any thing, to any group(i have like)

have an any idea ?

**Comment by jojoba2010** [comment]
hi.
i wanna send video to telegram to group via TLSharp
do you know how to do that.!
https://telegram.me/jojoba2010

**Comment by MrRoundRobin** [comment]
Telesharp is a different project

**Comment by jojoba2010** [comment]
how to do via TLSharp.Core

**Comment by jojoba2010** [comment]
await client.SendUploadedDocument
or
await client.SendUploadedPhoto(
