### ISSUE TITLE
Forbidden: bot was blocked by the user Exception

### ISSUE THREAD

**Issue by imantoop** [MrRoundRobin/telegram.bot.examples#96]
I stuck in an issue for long time and I wish you could help me.
It would be appreciate if you could response the below issues:
1- when a user of my bot "block and exit" and bot send him a massage, I got "Forbidden: bot was blocked by the user" error and my bot stop working until Telegram API refresh the service (I think it's every 24 h) but after that because of more "block and exit", My bot  stop working and this happen again and again so I lost my bot and have to create new one. what is wrong with my coding (if any). is there any solution for it?
2- if not, is there a solution for canceling all pending requests and is it possible to reuse my bot after Telegram Service refreshment?

**Comment by MrRoundRobin** [comment]
You have to catch the `apirequestexception`
